// Generated by CoffeeScript 1.9.3
(function() {
  var fget_plays, page;

  page = require('webpage').create();

  fget_plays = function(status) {
    var innings;
    if (status !== "success") {
      throw "failed to load page";
    }
    console.log("Parsing page");
    innings = page.evaluate(function() {
      return document.querySelector(".inning_nav");
    });
    console.log(innings);
    return console.log("Number of innings" + innings.children.length);
  };

  page.open("http://mlb.mlb.com/mlb/gameday/index.jsp?gid=2015_06_02_tormlb_wasmlb_1#game=2015_06_02_tormlb_wasmlb_1,game_state=Wrapup,game_tab=play-by-play", (function(_this) {
    return function(status) {
      return fget_plays(status);
    };
  })(this));

}).call(this);
