// Generated by CoffeeScript 1.9.3
(function() {
  var fget_wrap_links, fstatus, page;

  page = require('webpage').create();

  fstatus = function(status) {
    console.log("Status: " + status);
    if (status === "success") {
      console.log(page.content);
    }
    return phantom.exit();
  };

  fget_wrap_links = function(status) {
    var wraplinks;
    console.log("Status: " + status);
    if (status === "success") {
      wraplinks = page.evaluate(function() {
        return document.querySelectorAll(".wraplink");
      });
      console.log("Number of games:" + wraplinks.length);
      [].forEach.call(wraplinks, function(wraplink) {
        var link;
        console.log(wraplink);
        if (wraplink == null) {
          return;
        }
        console.log(wraplink.nodeType);
        link = wraplink.href;
        return console.log(link);
      });
    }
    return phantom.exit();
  };

  page.open("http://mlb.mlb.com/mlb/scoreboard/index.jsp#date=5/1/2015", fget_wrap_links);

}).call(this);
